services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
